services:
  backend:
    image: eclipse-temurin:21.0.6_7-jdk
    container_name: plapstudio-backend
    working_dir: /app
    ports:
      - "9000:9000"
    volumes:
      - ./proyecto-backend-PlapStudio:/app
      - gradle_cache:/root/.gradle
    command: >
      bash -c "
        chmod +x ./gradlew &&
        ./gradlew bootRun --args='--spring.profiles.active=docker'
      "
    environment:
      - TZ=America/Argentina/Buenos_Aires
      - SPRING_PROFILES_ACTIVE=docker
      - INTEGRATIONS_N8N_TURNO_CONFIRMADO_URL=http://n8n:5678/webhook-test/turno-confirmado
    depends_on:
      - postgres
      - n8n
    restart: unless-stopped

  frontend:
    image: node:20
    container_name: plapstudio-frontend
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./proyecto-frontend-PlapStudio:/app
      - frontend_node_modules:/app/node_modules
    command: >
      sh -c "
        npm install &&
        npm run dev -- --host 0.0.0.0
      "
    environment:
      - TZ=America/Argentina/Buenos_Aires
    depends_on:
      - backend
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: plapstudio-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db_agendify
      - POSTGRES_USER=agendify
      - POSTGRES_PASSWORD=agendify
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./n8n/n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  gradle_cache:
  frontend_node_modules:
  postgres_data:
