server:
  address: 0.0.0.0
  port: 9000
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_agendify
    username: agendify
    password: agendify
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
agendify:
  chatbot:
    gemini:
      enabled: true
      base-url: https://generativelanguage.googleapis.com
      api-key: ${GEMINI_API_KEY:}
      model: gemini-2.0-flash

---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/db_agendify
agendify:
  chatbot:
    gemini:
      enabled: true
      base-url: https://generativelanguage.googleapis.com
      api-key: ${GEMINI_API_KEY:}
      model: gemini-2.0-flash
